name = "party-popper-host"
pages_build_output_dir = "dist"
compatibility_date = "2024-01-01"

[env.production]
vars = { VITE_API_URL = "https://party-popper-api.workers.dev" }

[env.preview]
vars = { VITE_API_URL = "https://party-popper-api.workers.dev" }
