name = "party-popper-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[durable_objects]
bindings = [
  { name = "GAME", class_name = "GameDO" }
]

[[migrations]]
tag = "v1"
new_classes = ["GameDO"]

[dev]
port = 8787
local_protocol = "http"
